export const allProducts = [
    {   
        name: "Algoritmos E Lógica Da Programação",
        price: "48.99",
        img: "https://i.imgur.com/Kx9VQB1.jpeg",
        img02: "https://i.imgur.com/H88URtg.jpeg",
        category: "outros",
        author: "Marco A. Furlan de Souza",
        description: "Com linguagem simples e didática – sem, no entanto, fugir da complexidade do assunto –, o livro procura tornar prática a lógica de programação, além de mostrar aos estudantes um caminho mais adequado na construção dos algoritmos. O desenvolvimento do raciocínio lógico e da abstração de procedimentos e dados são as maiores dificuldades para os estudantes dos cursos introdutórios. Nesse sentido, os autores resolvem os problemas propostos passo a passo, apresentando todos os conceitos envolvidos por meio de fluxogramas e em conjunto com pseudocódigos.",
    },
    {
        name: "Padrões JavaScript",
        price: "52.60",
        img: "https://i.imgur.com/B0Zuybp.jpeg",
        img02: "https://i.imgur.com/oNx0u7E.jpeg",
        category: "javascript",
        author: "Stoyan Stefanov",
        description: "Recomenda-se que o leitor tenha experiência prévia em programação. Qual é a melhor maneira de desenvolver uma aplicação em JavaScript? Este livro, ao apresentar inúmeros padrões e as melhores práticas no JavaScript, vai ajudá-lo a responder a essa pergunta. Se você for um desenvolvedor experiente e está tentando resolver problemas relacionados a objetos, funções, herança e outras categorias específicas à linguagem, as abstrações e os modelos de código deste guia são ideais ― independentemente de você estar escrevendo uma aplicação JavaScript no lado do cliente, no lado do servidor ou uma aplicação desktop.",
    },
    {   
        name: "Código limpo: Habilidades práticas do Agile Software",
        price: "86.58",
        img: "https://i.imgur.com/ifnwVJb.jpeg",
        img02: "https://i.imgur.com/wJ47Mb6.jpeg",
        category: "outros",
        author: "Robert C. Martin",
        description: "Mesmo um código ruim pode funcionar. Mas se ele não for limpo, pode acabar com uma empresa de desenvolvimento. Perdem-se a cada ano horas incontáveis e recursos importantes devido a um código mal escrito. Mas não precisa ser assim.O renomado especialista em software, Robert C. Martin, apresenta um paradigma revolucionário com Código limpo: Habilidades Práticas do Agile Software. Martin se reuniu com seus colegas do Mentor Object para destilar suas melhores e mais ágeis práticas de limpar códigos “dinamicamente” em um livro que introduzirá gradualmente dentro de você os valores da habilidade de um profissional de softwares e lhe tornar um programador melhor –mas só se você praticar.Que tipo de trabalho você fará? Você lerá códigos aqui, muitos códigos. E você deverá descobrir o que está correto e errado nos códigos. E, o mais importante, você terá de reavaliar seus valores profissionais e seu comprometimento com o seu ofício.",
    },
    {
        name: "Pense em Python: Pense Como um Cientista da Computação",
        price: "80.80",
        img: "https://i.imgur.com/hw8vwTU.jpeg",
        img02: "https://i.imgur.com/jckvE1S.jpeg",
        category: "python",
        author: "Allen B. Downey",
        description: "Se você quer aprender como programar, usar Python é uma ótima forma de começar. Este guia prático apresenta a linguagem passo a passo, começando com conceitos de programação básicos antes de chegar a funções, recursividade, estruturas de dados e design orientado a objeto. Esta edição e seu código de apoio foram atualizados para o Python 3.",
    },
    {
        name: "Typescript – Gerando O Javascript Do Futuro",
        price: "75.67",
        img: "https://i.imgur.com/JcPmKan.jpeg",
        img02: "https://i.imgur.com/hRa0TMC.jpeg",
        category: "javascript",
        author: "Marcelo Soares Da Costa",
        description: "TypeScript é uma linguagem de script, sua sintaxe é um superconjunto de JavaScript, ou seja, todo código JavaScript também é um código TypeScript válido, é uma forma de se escrever o JavaScript do futuro e transformá-lo em JavaScript corrente, suportado pelos navegadores. Foi considerada pelo público a 3ª linguagem 'mais amada', de acordo com uma pesquisa conduzida pelo site Stack Overflow em 2017. Tem por objetivo permitir que escreva um código com uma linguagem mais humana, mais fácil de compreender, adicionando recursos ao JavaScript convencional. Foi adotado como linguagem oficial pelo Google e pela Microsoft, que reuniram esforços em conjunto para desenvolverem soluções com ênfase em mobile first, ou seja, focado para o uso em Smartphones. O objetivo deste livro é ajudá-lo no estudo e conhecimento desta nova abordagem de desenvolvimento de aplicações com o TypeScript, que tem claros objetivos traçados, e fazer com que o desenvolvimento do seu código de programação use um entendimento e raciocínio mais humano.",
    },
    {
        name: "HTML5: a Linguagem de Marcação que Revolucionou a Web",
        price: "45.00",
        img: "https://i.imgur.com/AFAz4dn.jpeg",
        img02: "https://i.imgur.com/BesSvdr.jpeg",
        category: "html",
        author: "Maurício Samy Silva",
        description: "HTML5 é a linguagem de marcação que amplia de forma surpreendente as funcionalidades da HTML, alterando de maneira significativa como você desenvolve para a web. Trata-se da mais extensa especificação para a HTML focada em criar funcionalidades para desenvolvimento não só de sites, mas também de aplicações de internet rica (RIA). Maujor aborda as funcionalidades da HTML5, de forma clara, em linguagem didática, mostrando vários exemplos práticos em funcionamento no site do livro.",
    },
    {
        name: "Refatoração de CSS: Organize Suas Folhas de Estilo com Sucesso",
        price: "45.70",
        img: "https://i.imgur.com/tjCQOwO.jpeg",
        img02: "https://i.imgur.com/TSOqW9A.jpeg",
        category: "css",
        author: "Steve Lindstrom",
        description: "Revisar seu código a fim de remover redundâncias e inconsistências – processo conhecido como refatoração – é uma prática comum quando usamos linguagens de programação. Com este guia prático, o autor Steve Lindstrom mostra não só como estruturar o CSS para construir sites responsivos e fáceis de usar, mas também como utilizar a refatoração e criar um CSS mais legível e possível de manter. Um bom CSS é essencial para a aparência dos sites modernos – é tão importante quanto o HTML que determina a apresentação do site e o JavaScript que executa a aplicação. Não importa se você está iniciando seu primeiro projeto de CSS ou se está organizando um código existente, este livro apresenta estratégias para construir uma base de código CSS que esteja de acordo com os princípios de uma boa arquitetura.",
    },
    {
        name: "Introdução à Linguagem SQL: Abordagem Prática Para Iniciantes",
        price: "41.80",
        img: "https://i.imgur.com/MechFqq.jpeg",
        img02: "https://i.imgur.com/MechFqq.jpeg",
        category: "sql",
        author: "Thomas Nield",
        description: "Atualmente as empresas estão coletando dados a taxas exponenciais e mesmo assim poucas pessoas sabem como acessá-los de maneira relevante. Se você trabalha em uma empresa ou é profissional de TI, este curto guia prático lhe ensinará como obter e transformar dados com o SQL de maneira significativa. Você dominará rapidamente os aspectos básicos do SQL e aprenderá como criar seus próprios bancos de dados. O autor Thomas Nield fornece exercícios no decorrer de todo o livro para ajudá-lo a praticar em casa suas recém descobertas aptidões no uso do SQL, sem precisar empregar um ambiente de servidor de banco de dados. Além de aprender a usar instruções-chave do SQL para encontrar e manipular seus dados, você descobrirá como projetar e gerenciar eficientemente bancos de dados que atendam às suas necessidades.",
    },
    {
        name: "SQL Para Análise de Dados: Técnicas Avançadas Para Transformar Dados em Insights",
        price: "80.10",
        img: "https://i.imgur.com/SjBdHnU.jpeg",
        img02: "https://i.imgur.com/SjBdHnU.jpeg",
        category: "sql",
        devas: "femme",
        imgDevas: "https://i.imgur.com/4eh2CK6.jpeg",
        author: "Cathy Tanimura",
        description: "Com a explosão do uso de dados, do poder computacional e dos data warehouses na nuvem, o SQL tornou-se uma ferramenta ainda mais indispensável para o cientista de dados ou o analista experiente. Este livro prático revela maneiras novas e ainda desconhecidas de você melhorar suas habilidades em SQL, resolver problemas e aproveitar ao máximo os recursos do SQL como parte de seu fluxo de trabalho. Você aprenderá a usar funções SQL comuns e inusitadas, como as junções, funções de janela, subconsultas, e expressões regulares, de maneiras novas e avançadas – e também a combinar técnicas do SQL para atingir seus objetivos com mais rapidez, com um código de fácil compreensão. Se você trabalha com bancos de dados SQL, esta é uma referência indispensável. • Aprenda as principais etapas para a preparação de seus dados para análise • Execute análises de séries temporais usando as manipulações de data e hora do SQL • Use a análise de coorte para investigar como os grupos mudam com o tempo • Use as funções e os operadores poderosos do SQL para a análise de texto • Detecte anomalias em seus dados e substitua-as por valores alternativos • Estabeleça causalidade usando a análise experimental, também conhecida como teste A/B.",
    },
    {
        name: "SQL Guia Prático: Um guia para o uso de SQL",
        price: "79.00",
        img: "https://i.imgur.com/NrgUwJE.jpeg",
        img02: "https://i.imgur.com/NrgUwJE.jpeg",
        category: "sql",
        devas: "femme",
        imgDevas: "https://i.imgur.com/I2tspw5.jpeg",
        author: "Alice Zhao",
        description: "Se você usa SQL em seu trabalho diário como analista de dados, cientista de dados ou engenheiro de dados, este guia prático será o material de consulta ideal para o seu dia a dia. Você encontrará muitos exemplos abordando as complexidades da linguagem e os aspectos-chave do SQL quando usado no Microsoft SQL Server, MySQL, Oracle Database, PostgreSQL e SQLite. Nesta edição atualizada, a autora Alice Zhao descreve como esses sistemas de gerenciamento de banco de dados implementam a sintaxe SQL tanto para consultar quanto para fazer alterações em um banco de dados. Você verá detalhes sobre tipos de dados e conversões, a sintaxe das expressões regulares, as funções de janela, pivotagem e despivotagem e muito mais.",
    },
    {
        name: "Jornada Python: uma jornada imersiva na aplicabilidade de uma das mais poderosas linguagens de programação do mundo",
        price: "89.78",
        img: "https://i.imgur.com/85BAz5I.jpeg",
        img02: "https://i.imgur.com/85BAz5I.jpeg",
        category: "python",
        devas: "femme",
        imgDevas: "https://i.imgur.com/Uo3ftXt.jpeg",
        author: "Tatiana Escovedo",
        description: "Livro Jornada Phyton: uma jornada imersiva na aplicabilidade de uma das mais poderosas linguagens de programação do mundo. Neste livro você será guiado em uma viagem chamada 'Jornada Python', iniciando com os fundamentos da linguagem, passando por orientação a objetos, boas práticas de programação e chegando a alguns assuntos mais avançados, como o desenvolvimento de aplicações web e ciência de dados. Esperamos vocês. Tenha uma boa viagem!",
    },
    {
        name: "Microsserviços prontos para a produção: Construindo sistemas padronizados em uma organização de engenharia de software",
        price: "36.30",
        img: "https://i.imgur.com/HQcYOau.jpeg",
        img02: "https://i.imgur.com/HQcYOau.jpeg",
        category: "outros",
        devas: "femme",
        imgDevas: "https://i.imgur.com/dNJxtpU.jpeg",
        author: "Susan Rigetti",
        description: "Um dos maiores desafios para as empresas que adotaram a arquitetura de microsserviços é a falta de padronização de arquitetura – operacional e organizacional. Depois de dividir uma aplicação monolítica ou construir um ecossistema de microsserviços a partir do zero, muitos engenheiros se perguntam o que vem a seguir. Neste livro prático, a autora Susan Fowler apresenta com profundidade um conjunto de padrões de microsserviço, aproveitando sua experiência de padronização de mais de mil microsserviços do Uber. Você aprenderá a projetar microsserviços que são estáveis, confiáveis, escaláveis, tolerantes a falhas, de alto desempenho, monitorados, documentados e preparados para qualquer catástrofe.",
    },
    {
        name: "Engenharia de Confiabilidade do Google: Como o Google administra seus sistemas de produção",
        price: "93.70",
        img: "https://i.imgur.com/JPk8Sbp.jpeg",
        img02: "https://i.imgur.com/JPk8Sbp.jpeg",
        category: "outros",
        devas: "femme",
        imgDevas: "https://i.imgur.com/Je2ZOYu.jpeg",
        author: "Betsy Beyer",
        description: "A maior parte do tempo de vida de um sistema de software se dá em seu uso, e não no design ou na implementação. Então, por que a sabedoria convencional insiste que os engenheiros de software devam se concentrar principalmente nas fases de design e de desenvolvimento dos sistemas computacionais de larga escala? Nesta coletânea de dissertações e artigos, membros essenciais da equipe de SRE (Site Reliability Engineering – Engenharia de Confiabilidade) do Google explicam como e por que seu comprometimento com todo o ciclo de vida tem permitido que a empresa desenvolva, implante, monitore e mantenha alguns dos maiores sistemas de software do mundo com sucesso. Você conhecerá os princípios e as práticas que possibilitam aos engenheiros do Google deixar os sistemas mais escaláveis, confiáveis e eficientes – lições que podem ser diretamente aplicáveis à sua empresa.",
    },
    {
        name: "Software Architecture: The Hard Parts (English Edition)",
        price: "144.99",
        img: "https://i.imgur.com/0UM5ywP.jpeg",
        img02: "https://i.imgur.com/0UM5ywP.jpeg",
        category: "outros",
        devas: "femme",
        imgDevas: "https://i.imgur.com/JQg3ElQ.jpeg",
        author: "Zhamak Dehghani",
        description: "There are no easy decisions in software architecture. Instead, there are many hard parts--difficult problems or issues with no best practices--that force you to choose among various compromises. With this book, you'll learn how to think critically about the trade-offs involved with distributed architectures. Architecture veterans and practicing consultants Neal Ford, Mark Richards, Pramod Sadalage, and Zhamak Dehghani discuss strategies for choosing an appropriate architecture. By interweaving a story about a fictional group of technology professionals--the Sysops Squad--they examine everything from how to determine service granularity, manage workflows and orchestration, manage and decouple contracts, and manage distributed transactions to how to optimize operational characteristics, such as scalability, elasticity, and performance.",
    },
    {
        name: "Designing Machine Learning Systems (English Edition)",
        price: "189.15",
        img: "https://i.imgur.com/sQThqYf.jpeg",
        img02: "https://i.imgur.com/sQThqYf.jpeg",
        category: "outros",
        devas: "femme",
        imgDevas: "https://i.imgur.com/P24czOv.jpeg",
        author: "Chip Huyen",
        description: "Machine learning systems are both complex and unique. Complex because they consist of many different components and involve many different stakeholders. Unique because they're data dependent, with data varying wildly from one use case to the next. In this book, you'll learn a holistic approach to designing ML systems that are reliable, scalable, maintainable, and adaptive to changing environments and business requirements. Author Chip Huyen, co-founder of Claypot AI, considers each design decision--such as how to process and create training data, which features to use, how often to retrain models, and what to monitor--in the context of how it can help your system as a whole achieve its objectives. The iterative framework in this book uses actual case studies backed by ample references.",
    },
    {
        name: "Database Reliability Engineering: Designing and Operating Resilient Database Systems (English Edition)",
        price: "74.89",
        img: "https://i.imgur.com/XHhGMf2.jpeg",
        img02: "https://i.imgur.com/XHhGMf2.jpeg",
        category: "database",
        devas: "femme",
        imgDevas: "https://i.imgur.com/CQhngmz.jpeg",
        author: "Charity Majors",
        description: "The infrastructure-as-code revolution in IT is also affecting database administration. With this practical book, developers, system administrators, and junior to mid-level DBAs will learn how the modern practice of site reliability engineering applies to the craft of database architecture and operations. Authors Laine Campbell and Charity Majors provide a framework for professionals looking to join the ranks of today’s database reliability engineers (DBRE).",
    },
    {
        name: "SVG Animations: From Common UX Implementations to Complex Responsive Animation (English Edition)",
        price: "214.00",
        img: "https://i.imgur.com/F5VFRYE.jpeg",
        img02: "https://i.imgur.com/F5VFRYE.jpeg",
        category: "svg",
        devas: "femme",
        imgDevas: "https://i.imgur.com/BFfZBIG.jpeg",
        author: "Sarah Drasner",
        description: "SVG is extremely powerful, with its reduced HTTP requests and crispness on any display. It becomes increasingly more interesting as you explore its capabilities for responsive animation and performance boons. When you animate SVG, you must be aware of normal image traits like composition, color, implementation, and optimization. But when you animate, it increases the complexity of each of these factors exponentially.",
    },
    {
        name: "JavaScript from Beginner to Professional: Learn JavaScript quickly by building fun, interactive, and dynamic web apps, games, and pages (English Edition)",
        price: "164.99",
        img: "https://i.imgur.com/MyqWg3C.jpeg",
        img02: "https://i.imgur.com/MyqWg3C.jpeg",
        category: "javascript",
        devas: "femme",
        imgDevas: "https://i.imgur.com/fiAimWI.jpeg",
        author: "Maaike van Putten",
        description: "This book demonstrates the capabilities of JavaScript for web application development by combining theoretical learning with code exercises and fun projects that you can challenge yourself with. The guiding principle of the book is to show how straightforward JavaScript techniques can be used to make web apps ranging from dynamic websites to simple browser-based games. JavaScript from Beginner to Professional focuses on key programming concepts and Document Object Model manipulations that are used to solve common problems in professional web applications. These include data validation, manipulating the appearance of web pages, working with asynchronous and concurrent code.",
    },
    {
        name: "Java Memory Management: A comprehensive guide to garbage collection and JVM tuning (English Edition)",
        price: "168.99",
        img: "https://i.imgur.com/my1o01I.jpeg",
        img02: "https://i.imgur.com/my1o01I.jpeg",
        category: "java",
        devas: "femme",
        imgDevas: "https://i.imgur.com/fiAimWI.jpeg",
        author: "Maaike van Putten",
        description: "Understanding how Java organizes memory is important for every Java professional, but this particular topic is a common knowledge gap for many software professionals. Having in-depth knowledge of memory functioning and management is incredibly useful in writing and analyzing code, as well as debugging memory problems. In fact, it can be just the knowledge you need to level up your skills and career. In this book, you'll start by working through the basics of Java memory. After that, you'll dive into the different segments individually. You'll explore the stack, the heap, and the Metaspace. Next, you'll be ready to delve into JVM standard garbage collectors. The book will also show you how to tune, monitor and profile JVM memory management. Later chapters will guide you on how to avoid and spot memory leaks. By the end of this book, you'll have understood how Java manages memory and how to customize it for the benefit of your applications.",
    },
    {
        name: "CSS: The Definitive Guide: Visual Presentation for the Web (English Edition)",
        price: "62.69",
        img: "https://i.imgur.com/Jt8wogD.jpeg",
        img02: "https://i.imgur.com/Jt8wogD.jpeg",
        category: "css",
        devas: "femme",
        imgDevas: "https://i.imgur.com/hwhRbNy.jpeg",
        author: "Estelle Weyl",
        description: "If yo’re a web designer or app developer interested in sophisticated page styling, improved accessibility, and saving time and effort, this book is for you. This revised edition provides a comprehensive guide to CSS implementation, along with a thorough review of the latest CSS specifications. CSS is a constantly evolving language for describing the presentation of web content on screen, printers, speech synthesizers, screen readers, and chat windows. It is used by all browsers on all screen sizes on all types of IoT devices, including phones, computers, video games, televisions, watches, kiosks, and auto consoles. Authors Eric Meyer and Estelle Weyl show you how to improve user experience, speed development, avoid potential bugs, and add life and depth to your applications through layout, transitions and animations, borders, backgrounds, text properties, and many other tools and techniques.",
    },
    {
        name: "Flexbox in CSS (English Edition)",
        price: "24.99",
        img: "https://i.imgur.com/rnTXWcN.jpeg",
        img02: "https://i.imgur.com/rnTXWcN.jpeg",
        category: "css",
        devas: "femme",
        imgDevas: "https://i.imgur.com/hwhRbNy.jpeg",
        author: "Estelle Weyl",
        description: "Layout designers rejoice: CSS finally has an update that will make your lives easier. Flexible box layout, often called Flexbox, frees you from the challenges of creating layouts with floats and padding? and lets you specify containers and their contents instead. The new model means you can specify the directions in which material flows, how content wraps, and the ways components can expand to fill a space. Whether you've been creating large sites or small, fixed sites or responsive sites, flexbox will simplify your work.",
    },
    {
        name: "Transitions and Animations in CSS: Adding Motion with CSS (English Edition)",
        price: "122.97",
        img: "https://i.imgur.com/GQc5vBr.jpeg",
        img02: "https://i.imgur.com/GQc5vBr.jpeg",
        category: "css",
        devas: "femme",
        imgDevas: "https://i.imgur.com/hwhRbNy.jpeg",
        author: "Estelle Weyl",
        description: "This practical book shows you how CSS transitions and animations provide a way to control how a property changes from one value to the next over time. You can make the property value change gradually, creating pleasant and hopefully unobtrusive effects. CSS transitions let you decide which properties to animate, how long to wait before the animation starts, how long the transition should take, and how the transition will proceed—all of which are customizable.",
    },
    {
        name: "HTML5 & CSS3 For The Real World: Powerful HTML5 and CSS3 Techniques You Can Use Today! (English Edition)",
        price: "63.54",
        img: "https://i.imgur.com/JXnwybT.jpeg",
        img02: "https://i.imgur.com/JXnwybT.jpeg",
        category: ["css", "html"],
        devas: "femme",
        imgDevas: "https://i.imgur.com/hwhRbNy.jpeg",
        author: "Estelle Weyl",
        description: "HTML5 and CSS3 for the Real World is your perfect introduction to the latest generation of web technologies. This easy-to-follow guide covers everything you need to know to get started today. You'll master the semantic markup available in HTML5, as well as how to use CSS3 to create amazing-looking websites without resorting to complex workarounds.",
    },
    {
        name: "Mobile HTML5: Using the Latest Today (English Edition)",
        price: "154.01",
        img: "https://i.imgur.com/aJnnBm4.jpeg",
        img02: "https://i.imgur.com/aJnnBm4.jpeg",
        category: "html",
        devas: "femme",
        imgDevas: "https://i.imgur.com/hwhRbNy.jpeg",
        author: "Estelle Weyl",
        description: "Build kickass websites and applications for all mobile (and non-mobile) platforms by adding HTML5 and CSS3 to your web development toolkit. With this hands-on book, you’ll learn how to develop web apps that not only work on iOS, Android, Blackberry, and Windows Phone, but also perform well and provide good user experience. With lots of code and markup examples, you’ll learn best practices for using HTML5 features, including new web forms, SVG, Canvas, localStorage, and related APIs. You’ll also get an in-depth look at CSS3, and discover how to design apps for large monitors and tiny screens alike.",
    },
];